const { Client, Intents, Collection } = require('discord.js'); //discord module for interation with discord api
const Discord = require('discord.js'); //discord module for interation with discord api
var babadata = require('./babotdata.json'); //baba configuration file
const { setCommandRoles } = require('./helperFunc');

const bot = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.DIRECT_MESSAGES], partials: ["CHANNEL"]});
bot.login(babadata.token); //login

bot.on('ready', function (evt) 
{
	console.log('Connected');
	var gld = bot.guilds.cache.get(babadata.guildId);
	setCommandRoles(gld)
});

//not shure what this does also but it was in jeremy's code so -- generated by Github Copilot

//stop the bot manually when you see all the commands as runnable (admins)

// broken due to discord api changes